name: my_scan_kp
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.2+1
  cloud_firestore: ^0.14.3+1
  qr_code_scanner: ^0.0.13
  flutter_statusbarcolor: ^0.2.3
  flutter_tabler_icons: ^1.0.2
  flutter_svg: ^0.19.0
  json_annotation: ^3.1.1
  lottie: ^0.7.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  json_serializable: ^3.5.1
  build_runner: ^1.10.11

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

